name: build blog

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: "install pnpm"
        run: npm install -g pnpm

      - name: "pnpm install"
        run: pnpm install

      - name: gen blog
        run: export TZ='Asia/Shanghai' && pnpm hexo generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: pages
          force_orphan: true
          commit_message: ${{ github.event.head_commit.message }}
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
