name: build blog

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Shanghai"
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: "npm install"
        run: |
          npm install -g pnpm
          pnpm install --no-frozen-lockfile

      - name: "setup pandoc"
        run: |
          curl -s -L https://github.com/jgm/pandoc/releases/download/2.19.2/pandoc-2.19.2-linux-amd64.tar.gz | tar xvzf - -C ./
          mkdir -p ~/.local/bin
          mv $(pwd)/pandoc-2.19.2/bin/pandoc ~/.local/bin/

      - name: gen blog
        run: pnpm hexo g

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: pages
          force_orphan: true
          commit_message: ${{ github.event.head_commit.message }}
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
